// Generated by build-gallery-manifest.js. Edit captions in this file after adding images.
window.galleryData = [
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-12.jpg",
    "alt": "DSC02905.JPG.jpeg",
    "caption": "DSC02905.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-13.jpg",
    "alt": "DSC02909.JPG.jpeg",
    "caption": "DSC02909.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-14.jpg",
    "alt": "DSC02911.JPG.jpeg",
    "caption": "DSC02911.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-15.jpg",
    "alt": "DSC02928.JPG.jpeg",
    "caption": "DSC02928.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-16.jpg",
    "alt": "DSC02927.JPG.jpeg",
    "caption": "DSC02927.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-17.jpg",
    "alt": "DSC02922.JPG.jpeg",
    "caption": "DSC02922.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/CLUB PHOTOSHOOTS/photo-19.jpg",
    "alt": "DSC02906.JPG.jpeg",
    "caption": "DSC02906.JPG.jpeg",
    "folder": "2026/CLUB PHOTOSHOOTS",
    "folderLabel": "CLUB PHOTOSHOOTS"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-1.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-2.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-3.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-4.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-5.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-6.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-7.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-8.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-9.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-10.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  },
  {
    "image": "gallery/2026/DSCI 2 DAY BOOTCAMP 2026/photo-11.jpg",
    "alt": "DSCI 2 DAY BOOTCAMP 2026",
    "caption": "DSCI 2 DAY BOOTCAMP 2026",
    "folder": "2026/DSCI 2 DAY BOOTCAMP 2026",
    "folderLabel": "DSCI 2 DAY BOOTCAMP 2026"
  }


];
